[toolchain]
channel = "stable"
components = [ "rustfmt", "clippy", "rust-std", "rust-analyzer", "rust-docs" ]
targets = [ "aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin", "x86_64-pc-windows-gnu", "x86_64-pc-windows-msvc", "x86_64-unknown-linux-musl", "aarch64-unknown-linux-musl", "x86_64-unknown-netbsd" ]
profile = "default"
